remote_theme: jekyll/minima

title: DuckDB GSheets

include:
  - privacy.md
  - ./README.md

exclude:
  - "**/*"
  - "**/*.md"

plugins:
  - jekyll-sitemap

minima:
  skin: dark

header_pages:
  - README.md
  - privacy.md

permalink: pretty

social_links:
- { platform: github,  user_url: "https://github.com/archiewood/duckdb-gsheets" }
