remote_theme: jekyll/minima

include:
  - README.md

minima:
  skin: dark

header_pages:
  - README.md
social_links:
- { platform: github,         user_url: "https://github.com/archiewood/duckdb-gsheets" }
