remote_theme: jekyll/minima

title: DuckDB GSheets

include:
  - README.md
  - PRIVACY.md

exclude:
  - duckdb/**
  - docs/**
  - extension-ci-tools/**
  - src/**
  - test/**
  - third_party/**
  - vcpkg_installed/**

plugins:
  - jekyll-sitemap

minima:
  skin: dark

header_pages:
  - README.md
  - PRIVACY.md

social_links:
- { platform: github,  user_url: "https://github.com/archiewood/duckdb-gsheets" }
